/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionistDashboardRouteImport } from './routes/receptionist.dashboard'
import { Route as PatientQueueRouteImport } from './routes/patient.queue'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as AuthRoleRouteImport } from './routes/auth.$role'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistDashboardRoute = ReceptionistDashboardRouteImport.update({
  id: '/receptionist/dashboard',
  path: '/receptionist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientQueueRoute = PatientQueueRouteImport.update({
  id: '/patient/queue',
  path: '/patient/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/patient/book',
  path: '/patient/book',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/$role',
  path: '/auth/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/auth/$role': typeof AuthRoleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/auth/$role': typeof AuthRoleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queue': typeof QueueRoute
  '/auth/$role': typeof AuthRoleRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/queue': typeof PatientQueueRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/queue'
    | '/auth/$role'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/patient/queue'
    | '/receptionist/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue'
    | '/auth/$role'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/patient/queue'
    | '/receptionist/dashboard'
  id:
    | '__root__'
    | '/'
    | '/queue'
    | '/auth/$role'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/dashboard'
    | '/patient/profile'
    | '/patient/queue'
    | '/receptionist/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueueRoute: typeof QueueRoute
  AuthRoleRoute: typeof AuthRoleRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientQueueRoute: typeof PatientQueueRoute
  ReceptionistDashboardRoute: typeof ReceptionistDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist/dashboard': {
      id: '/receptionist/dashboard'
      path: '/receptionist/dashboard'
      fullPath: '/receptionist/dashboard'
      preLoaderRoute: typeof ReceptionistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/queue': {
      id: '/patient/queue'
      path: '/patient/queue'
      fullPath: '/patient/queue'
      preLoaderRoute: typeof PatientQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/patient/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$role': {
      id: '/auth/$role'
      path: '/auth/$role'
      fullPath: '/auth/$role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueueRoute: QueueRoute,
  AuthRoleRoute: AuthRoleRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientQueueRoute: PatientQueueRoute,
  ReceptionistDashboardRoute: ReceptionistDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
